### ISSUE TITLE
Error in MLB PlayerID lookup

### ISSUE THREAD

**Issue by mediumwalter** [edwarddistel/yahoo-fantasy-baseball-automater#100]
Hello,

I am getting an error in PlayerID lookup

Running on MacOS Ventura 13.3.1

Targeting 2023-5-30
Getting probable pitchers...
Getting my players...
Getting stats...
Acquiring player statistics from MLB.com....Error in MLB PlayerID lookup of Will Smith on LAD: AxiosError: Request failed with status code 502
No player stats for Will Smith
.Error in MLB PlayerID lookup of Matt Olson on ATL: AxiosError: Request failed with status code 502
No player stats for Matt Olson
.Error in MLB PlayerID lookup of Luis García on WSH: AxiosError: Request failed with status code 502
No player stats for Luis García
.Error in MLB PlayerID lookup of Jeimer Candelario on WSH: AxiosError: Request failed with status code 502
No player stats for Jeimer Candelario
.Error in MLB PlayerID lookup of Amed Rosario on CLE: AxiosError: Request failed with status code 502
No player stats for Amed Rosario
.Error in MLB PlayerID lookup of Bryan Reynolds on PIT: AxiosError: Request failed with status code 502
No player stats for Bryan Reynolds
.Error in MLB PlayerID lookup of Ji Hwan Bae on PIT: AxiosError: Request failed with status code 502
No player stats for Ji Hwan Bae
.Error in MLB PlayerID lookup of Josh Naylor on CLE: AxiosError: Request failed with status code 502
No player stats for Josh Naylor
.Error in MLB PlayerID lookup of Jose Caballero on SEA: AxiosError: Request failed with status code 502
No player stats for Jose Caballero
.Error in MLB PlayerID lookup of Christian Bethancourt on TB: AxiosError: Request failed with status code 502
No player stats for Christian Bethancourt
.Error in MLB PlayerID lookup of Gavin Sheets on CWS: AxiosError: Request failed with status code 502
No player stats for Gavin Sheets
.Error in MLB PlayerID lookup of Masataka Yoshida on BOS: AxiosError: Request failed with status code 502
No player stats for Masataka Yoshida
.Error in MLB PlayerID lookup of Alex Verdugo on BOS: AxiosError: Request failed with status code 502
No player stats for Alex Verdugo
.Error in MLB PlayerID lookup of Trent Grisham on SD: AxiosError: Request failed with status code 502
No player stats for Trent Grisham
.Error in MLB PlayerID lookup of Chris Bassitt on TOR: AxiosError: Request failed with status code 502
No player stats for Chris Bassitt
.Error in MLB PlayerID lookup of MacKenzie Gore on WSH: AxiosError: Request failed with status code 502
No player stats for MacKenzie Gore
.Error in MLB PlayerID lookup of Justin Topa on SEA: AxiosError: Request failed with status code 502
No player stats for Justin Topa
.Error in MLB PlayerID lookup of Scott McGough on ARI: AxiosError: Request failed with status code 502
No player stats for Scott McGough
.Error in MLB PlayerID lookup of Nathan Eovaldi on TEX: AxiosError: Request failed with status code 502
No player stats for Nathan Eovaldi
.Error in MLB PlayerID lookup of Kutter Crawford on BOS: AxiosError: Request failed with status code 502
No player stats for Kutter Crawford
.Error in MLB PlayerID lookup of Ryan Weathers on SD: AxiosError: Request failed with status code 502
No player stats for Ryan Weathers
.Error in MLB PlayerID lookup of Jameson Taillon on CHC: AxiosError: Request failed with status code 502
No player stats for Jameson Taillon
.Error in MLB PlayerID lookup of Aaron Nola on PHI: AxiosError: Request failed with status code 502
No player stats for Aaron Nola
.Error in MLB PlayerID lookup of Trevor Story on BOS: AxiosError: Request failed with status code 502
No player stats for Trevor Story
.Error in MLB PlayerID lookup of José Alvarado on PHI: AxiosError: Request failed with status code 502
No player stats for José Alvarado
.Error in MLB PlayerID lookup of Jacob deGrom on TEX: AxiosError: Request failed with status code 502
No player stats for Jacob deGrom
.Error in MLB PlayerID lookup of Jose Miranda on MIN: AxiosError: Request failed with status code 502
No player stats for Jose Miranda
.Error in MLB PlayerID lookup of Elly De La Cruz on CIN: AxiosError: Request failed with status code 502
No player stats for Elly De La Cruz

Analyzing roster...
Building roster...
Sending to Yahoo...
Error with credentials in positionPlayer(): {
    "message": "Request failed with status code 400",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 400\n    at settle (/Users/corey/yahoo-fantasy-baseball-automater/node_modules/axios/dist/node/axios.cjs:1909:12)\n    at Unzip.handleStreamEnd (/Users/corey/yahoo-fantasy-baseball-automater/node_modules/axios/dist/node/axios.cjs:2989:11)\n    at Unzip.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 10000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/xml",
            "Authorization": "Bearer B1Fl0BOYvA_biAByeJ55q1b7aBqeSSkiTPKlKfS_mScxO3XAgshnN7vGc56iwRw41vinOvPKdFZQHXkZfwUJH2zwjO7BdAbZK3BXKvp.sUnFZEFPLEEhWSYNvcBLaWTVTGPw1AFWJufSWAPRo.cYDtvrInygk3PN5K433JRfxfT_ty1McAg0.k8Owmt0SNHy2ne3TSgH2UrGGgjPH3Lv7pa5dvwDcDuxYnKCDzY5_gYaUuisUUHuyImfxYkN1_QRkbEjlhA9zUj5gay3WpHSRzvDIByJJl16JrnsLlVhCwlp2PQhpgObb0kJJP5mbdoZJ2reUrOl0wIAeAv3mDfYA9XxHZBSTSsyh7Nghx8xqM.lBnr1fcbY_G6ONQu.QkVZ1j1_jeWeuGfjaTnDznJ4Xu9J2bJ9cbcH1FWtNAjNs1LxRq35S3fUXg8yfl6rkO5B5uDfEjCJuMWJARumG_.AyvM6wP91mFSPKrDtr6bGrQz1xNmdNzrj_7dZsOsnUbn3OxTYCCHal8HoKJtObo2uassHvR4VxNYvk9Kp11Y7Nw5oZC0rHADDynPpIWV1zmvESSkkYpUFZgh_mrTGtATWhXt8y95e17EI3x0NBQAZuOPWv4aal.vDSuP7rJarHd_C1bDGmtP7hZOUc4Wc0D9.lqfPp8NYdgusM7BmqCj16vQuQujr6jGhdQcnH8AV6TJCASONc6UL1_XMGbcBotgbt_d38jgLKhuV2TfL.CCkyyaK5llADkHPCJTZ1vaF_Eh9fhKxamgKS6eQ3t_SbYJwZXDN97HzFQth7T5g.aL7K_dtlHl1BuLEkEKq5wQhrVkRLoVZgD16WmHxVEJPIzWALbAnWsZjjH7j0lLhz9KU5I8TpENGAz9Y.If6qVO_445MqX4lNAkPSWQV_eOwPHx1JqOhBvnAGCZgWcrnUmZfbd2ylgYPWzPGyJsNx1b7IZJe1K1fyZmE2bNHNqYkiOnhJm3DGzLZ.cLoRRlx.lFAjiNo.b3zZA--",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36",
            "Content-Length": "180",
            "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "method": "put",
        "url": "https://fantasysports.yahooapis.com/fantasy/v2/team/422.l.115291.t.2/roster",
        "data": "<?xml version='1.0'?>\n<fantasy_content>\n    <roster>\n        <coverage_type>date</coverage_type>\n        <date>2023-05-30</date>\n        <players/>\n    </roster>\n</fantasy_content>"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 400
}

**Comment by edwarddistel** [comment]
Yeah, I've been sitting on a major overhaul of this tool for a while -- I need to release it. Hopefully within a month. My apologies.

**Comment by mediumwalter** [comment]
Ha no worries! I was just messing around with it for the first time.
