### ISSUE TITLE
Error with credentials in positionPlayer()

### ISSUE THREAD

**Issue by cjhaviland** [edwarddistel/yahoo-fantasy-baseball-automater#7]
Getting a 400 error when trying to do a PUT request. Not sure why that request is failing credentials but is grabbing my players without issue. I did notice that your setup configuration for Yahoo Developer API setup is the old version. Not sure if it's the redirect URL, but that should just be for authorization. Let me know if you need any other details!

``` console
Targeting 2021-6-21
Getting probable pitchers...
Getting my players...
Getting stats...
Acquiring player statistics from MLB.com......................................
Analyzing roster...
Building roster...
Sending to Yahoo...
<?xml version='1.0'?>
<fantasy_content>
    <roster>
        <coverage_type>date</coverage_type>
        <date>2021-06-21</date>
        <players>
            <player>
                <player_key>404.p.10992</player_key>
                <position>C</position>
            </player>
            <player>
                <player_key>404.p.10918</player_key>
                <position>1B</position>
            </player>
            <player>
                <player_key>404.p.9411</player_key>
                <position>2B</position>
            </player>
            <player>
                <player_key>404.p.10344</player_key>
                <position>3B</position>
            </player>
            <player>
                <player_key>404.p.11692</player_key>
                <position>SS</position>
            </player>
            <player>
                <player_key>404.p.10157</player_key>
                <position>CI</position>
            </player>
            <player>
                <player_key>404.p.11118</player_key>
                <position>OF</position>
            </player>
            <player>
                <player_key>404.p.10183</player_key>
                <position>Util</position>
            </player>
            <player>
                <player_key>404.p.8875</player_key>
                <position>BN</position>
            </player>
            <player>
                <player_key>404.p.9002</player_key>
                <position>BN</position>
            </player>
            <player>
                <player_key>404.p.9378</player_key>
                <position>BN</position>
            </player>
            <player>
                <player_key>404.p.9718</player_key>
                <position>BN</position>
            </player>
            <player>
                <player_key>404.p.9726</player_key>
                <position>BN</position>
            </player>
            <player>
                <player_key>404.p.10380</player_key>
                <position>BN</position>
            </player>
            <player>
                <player_key>404.p.10566</player_key>
                <position>BN</position>
            </player>
            <player>
                <player_key>404.p.10577</player_key>
                <position>BN</position>
            </player>
            <player>
                <player_key>404.p.11231</player_key>
                <position>BN</position>
            </player>
        </players>
    </roster>
</fantasy_content>
Error with credentials in positionPlayer(): {
    "message": "Request failed with status code 400",
    "name": "Error",
    "stack": "Error: Request failed with status code 400\n    at createError (D:\\Repos\\yahoo-fantasy-baseball-automater\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (D:\\Repos\\yahoo-fantasy-baseball-automater\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (D:\\Repos\\yahoo-fantasy-baseball-automater\\node_modules\\axios\\lib\\adapters\\http.js:260:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
    "config": {
        "url": "https://fantasysports.yahooapis.com/fantasy/v2/team/404.l.28975.t.4/roster",
        "method": "put",
        "data": "<?xml version='1.0'?>\n<fantasy_content>\n    <roster>\n        <coverage_type>date</coverage_type>\n        <date>2021-06-21</date>\n        <players>\n            <player>\n                <player_key>404.p.10992</player_key>\n        
        <position>C</position>\n            </player>\n            <player>\n                <player_key>404.p.10918</player_key>\n                <position>1B</position>\n            </player>\n            <player>\n                <player_key>404.p.9411</player_key>\n                <position>2B</position>\n            </player>\n            <player>\n                <player_key>404.p.10344</player_key>\n                <position>3B</position>\n            </player>\n            <player>\n
    <player_key>404.p.11692</player_key>\n                <position>SS</position>\n            </player>\n            <player>\n                <player_key>404.p.10157</player_key>\n                <position>CI</position>\n            </player>\n        
    <player>\n                <player_key>404.p.11118</player_key>\n                <position>OF</position>\n            </player>\n            <player>\n                <player_key>404.p.10183</player_key>\n                <position>Util</position>\n   
         </player>\n            <player>\n                <player_key>404.p.8875</player_key>\n                <position>BN</position>\n            </player>\n            <player>\n                <player_key>404.p.9002</player_key>\n                <position>BN</position>\n            </player>\n            <player>\n                <player_key>404.p.9378</player_key>\n        
        <position>BN</position>\n            </player>\n            <player>\n                <player_key>404.p.9718</player_key>\n                <position>BN</position>\n            </player>\n            <player>\n                <player_key>404.p.9726</player_key>\n                <position>BN</position>\n            </player>\n            <player>\n                <player_key>404.p.10380</player_key>\n                <position>BN</position>\n            </player>\n            <player>\n
    <player_key>404.p.10566</player_key>\n                <position>BN</position>\n            </player>\n            <player>\n                <player_key>404.p.10577</player_key>\n                <position>BN</position>\n            </player>\n        
    <player>\n                <player_key>404.p.11231</player_key>\n                <position>BN</position>\n            </player>\n        </players>\n    </roster>\n</fantasy_content>",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/xml",
            "Authorization": "Bearer TOKEN",     
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36",
            "Content-Length": 2505
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 10000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1
    }
}
```

**Comment by cjhaviland** [comment]
Looks like it's trying to put my IL players in my BN and one player is duplicated 5 times on my bench.

I also tried to modify the code because I have an extra UTIL spot and that seems to be showing up now.

**Comment by edwarddistel** [comment]
Yeah, there's some issues, I haven't had time to address -- just too busy. If you can fix and submit a PR, happy to review.

**Comment by edwarddistel** [comment]
Will release a new version of this tool this summer. Hopefully.
